package com.epam.bank.exceptions;

/**
 * The Class AccountNumberDoesnotExistException.
 */
public class AccountNumberDoesnotExistException extends Exception {

	/**
	 *  Generated By Eclipse.
	 */
	private static final long serialVersionUID = 1L;

	public AccountNumberDoesnotExistException() {
		super();
	}

	public AccountNumberDoesnotExistException(String message) {
		super(message);
	}

}
