package com.epam.bank.exceptions;

/**
 * Exception InSufficientAmountException
 * 
 * @author Nishant_Bansal
 */
public class InSufficientAmountException extends Exception {

	/**
	 * Generated By Eclipse.
	 */
	private static final long serialVersionUID = 1L;

	public InSufficientAmountException(String msg) {
		super(msg);
	}

}
