package com.epam.bank.exceptions;

/**
 * Exception InvalidAmountException
 * 
 * @author Nishant_Bansal
 *
 */
public class InvalidAmountException extends Exception {

	/**
	 * Generated By Eclipse
	 */
	private static final long serialVersionUID = 1L;

	public InvalidAmountException(String msg) {
		super(msg);
	}
}
